### ISSUE TITLE
Explaination of chassis controller commands

### ISSUE THREAD

**Issue by WinRobotics** [JoenHune/RoboMasterEP-ROS#2]
Hi Joen,

Thanks for sharing this wondering code sample for the robomaster. 

Am wondering if you can share more about your findings with regards on how do one initalize the robomaster EP.

I have tried to follow your code but i realized that when i manually send the message in this sequence:

1. command;
2. Reply -> ok;
3. chassis speed x 0 y 0 z 0;
4. Reply-> ok;

The robomaster will just move by itself, wondering if you can share any information about this? i assumed chass speed command is to set the speed to x = 0 m/s , y = 0 m/s and z = 0 m/s

**Comment by WinRobotics** [comment]
Hi Joen,

Wondering if you can share more about this

controller->set_chassis_speed() needs a short break-time (set moving speed back to 0 or another direction) to change robot's direction.

what do you mean by short break time?

**Comment by JoenHune** [comment]
Hi friend, 

Not clear enough for me to help you figuring out the problem but seems you had already found the right way to do your job?

Further discussions are welcome although i am not using this platform for a long time.  : )
